name: islamic_quiz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  get: ^4.6.5
  logger: ^1.0.0
  easy_separator: ^1.0.1
  blurhash_flutter: ^0.1.0
  cupertino_icons: ^1.0.2
  #google_fonts: 2.2.0
  flutter_zoom_drawer: ^2.1.2
  liquid_pull_to_refresh: ^3.0.1
  shimmer: ^2.0.0
  flutter_native_splash: 1.3.2

  cloud_firestore: 3.1.5
  firebase_core: 1.10.6
  firebase_auth: 3.3.5
  google_sign_in: 5.2.1
  firebase_storage: 10.2.5


  flutter_local_notifications: ^9.2.0
  path_provider: ^2.0.8
  http: ^0.13.4
  url_launcher: ^6.0.18



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_crashlytics_platform_interface: 3.1.13
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/DB/papers/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
    - family: Almarai
      fonts:
        - asset: assets/icons/Almarai.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#7424ed"
  color_dark: "#5d0ed2"
  android_gravity: center
  fullscreen: true
  image: assets/images/splash_logo.png